### ISSUE TITLE
Should all models be updated to accept UserID as int64?

### ISSUE THREAD

**Issue by iamelevich** [go-telegram/bot#18]
In types we have `UserID` as `int64`
https://github.com/go-telegram/bot/blob/de923f1916d5a45abf121e41f86ec01e1d20ac82/models/user.go#L11
But in params we have it as `int`. For example in `GetUserProfilePhotos`
https://github.com/go-telegram/bot/blob/de923f1916d5a45abf121e41f86ec01e1d20ac82/methods_params.go#L293

And it makes me really confusing about how to use it.

**Comment by negasus** [comment]
You right. W'll fix it soon

**Comment by iamelevich** [comment]
> You right. I'll fix it soon

If you didn't started I can create PR today for it.

**Comment by negasus** [comment]
Great. Waiting for PR

**Comment by iamelevich** [comment]
> Great. Waiting for PR

Please check: https://github.com/go-telegram/bot/pull/19
