### ISSUE TITLE
Release names

### ISSUE THREAD

**Issue by iamelevich** [go-telegram/bot#22]
Hi, probably it make sense to use version as release name? Because for now it's a little bit confusing to see on Changelog as release name and you need to go to the release and check tag to identify actual release version.

![CleanShot 2023-03-19 at 17 47 33@2x](https://user-images.githubusercontent.com/46163087/226191652-50fe5f81-66d1-4035-aa74-5ca8f6fa54d0.png)

**Comment by negasus** [comment]
Yes, it make sense. Thanks
