### ISSUE TITLE
WithLogger() option is required

### ISSUE THREAD

**Issue by Vasilesk** [go-telegram/bot#27]
WithLogger() bot option would be very cool for those who require structured log output

**Comment by negasus** [comment]
If you want to catch errors, you can use `WithErrorsHandler` option. 
I'll think about custom handler for debug message. 

I would not like to add the WithLogger option. I will be forced to come up with the most suitable interface, and anyway it will not suit everyone, I will have to write some adapters

**Comment by Vasilesk** [comment]
Thank you, `WithErrorsHandler` suits for errors but for debug it seems like everybody is forced to use global std logger 😅 So I suppose an alternative like interface with `Debugf(template string, args ...interface{})` method would be quite nice, especially as an optional parameter. The signature seems to be quite popular. And those who don't like it still can write adapters by themselves, still better than global logger as an only option.

> custom handler for debug messages

Sounds like something that will suit, I will wait for it then!
