### ISSUE TITLE
Store GetMe Result as Bot struct variable

### ISSUE THREAD

**Issue by xtianpu** [go-telegram/bot#35]
Hello! Can I request to store GetMe result after every GetMe call to Bot struct Variable?

I think this is a good idea so once GetMe is called, we can get the result like bot.Id or bot.Username rather than creating another variable to store GetMe result.

**Comment by negasus** [comment]
Calling `GetMe` on init is optional behavior. The user can skip it with the "With SkipGaMe()" option. I think we should leave this method call to collect data to the user's choice.

**Comment by xtianpu** [comment]
I got it, thanks!
