### ISSUE TITLE
Changes from Bot API 7.0

### ISSUE THREAD

**Issue by xprnio** [go-telegram/bot#54]
Telegram seemed to not have forgotten about Christmas and gave us all the gift of changes.

I wanted to ask whether anybody has already decided on taking it upon themselves to start bringing those changes into this library or is that currently up in the air?

If that's still up in the air, I am willing to offer my help in adding support for 7.0 since there are some features that I need which were broken with the major version change. As such, I would love to hear what else was broken with the update so I could start putting together a list which would prioritize that which used to work and now doesn't, and just working my way down the whole [changelog](https://core.telegram.org/bots/api#december-29-2023).

**Comment by negasus** [comment]
I plan to make updates soon )

**Comment by negasus** [comment]
Released v1.0.0
