### ISSUE TITLE
Use the 'MaybeInaccessibleMessage' type for callback query message

### ISSUE THREAD

**Issue by NiJeTi** [go-telegram/bot#62]
[Callback Query](https://core.telegram.org/bots/api#callbackquery)

Currently lib implements type `MaybeInaccessibleMessage`, but callback query does not use it. Instead it directly uses `InaccessibleMessage` type and thus no validation for callback message accessibility can be made.

**Comment by negasus** [comment]
Fixed #63 
Released v1.1.4

Thanks
