### ISSUE TITLE
http.ListenAndServeTLS webhook example

### ISSUE THREAD

**Issue by Dmitriy147** [go-telegram/bot#70]
Has anybody working example of webhook with cert? Unfortunately, all my attempts to run such bot were unsuccessfully!

**Comment by negasus** [comment]
The library provides a handler function and has nothing to do with creating a server. I guess you can test your code without the library with an empty handler. And when everything works, substitute the handler from the library.

Personally, I don't use webhooks. But usually I would use a proxy server in front of the application
