### ISSUE TITLE
hope to add a conversationexample

### ISSUE THREAD

**Issue by pd5200** [go-telegram/bot#72]
I hope to add a conversationexample.I thingmany people need it, but they don't know how to write it. It is hoped that an example can be provided.
like:
https://github.com/PaulSonOfLars/gotgbot/blob/v2/samples/conversationBot/main.go

**Comment by gokhanaltun** [comment]
> I hope to add a conversationexample.I thingmany people need it, but they don't know how to write it. It is hoped that an example can be provided. like: https://github.com/PaulSonOfLars/gotgbot/blob/v2/samples/conversationBot/main.go

I made an example like this for myself, you can review and use it.

https://github.com/gokhanaltun/go-telegram-bot/blob/main/examples/conversation_handler/main.go

**Comment by vagrantvaquita** [comment]
> I made an example like this for myself, you can review and use it.
> 
> https://github.com/gokhanaltun/go-telegram-bot/blob/main/examples/conversation_handler/main.go

This is a good contribution! Why hasn't been merge yet?

**Comment by gokhanaltun** [comment]
> > I made an example like this for myself, you can review and use it.
> > https://github.com/gokhanaltun/go-telegram-bot/blob/main/examples/conversation_handler/main.go
> 
> This is a good contribution! Why hasn't been merge yet?

I don't know, after waiting for about a week without receiving a response, I withdrew the pull request and decided to share it only on my own account. I continue to contribute there. I just added an example for using the webapp.

https://github.com/gokhanaltun/go-telegram-bot/blob/main/examples/web_app/main.go
