### ISSUE TITLE
Send foto, send document

### ISSUE THREAD

**Issue by vv198x** [go-telegram/bot#8]
Greetings, I noticed here that the example does not work: send_photo. Also I can't send the document.

**Comment by negasus** [comment]
`send_photo` example operate with previously uploaded phote. Try `send_photo_upload` example with run `go run ./examples/send_photo_upload` and send any text to the bot

**Comment by negasus** [comment]
Also I make `upload document` example. Maybe I make some fixes, if needed

**Comment by negasus** [comment]
I made a new release. Added `upload_document` demo

**Comment by vv198x** [comment]
Yes, the send_photo_upload worked. The senddocument was missing a model. The document i was sent via sendmediagroup. Я проверяю senddocument. Thanx!
