### ISSUE TITLE
Inline keyboard example - Buttons' callback doesn't get run

### ISSUE THREAD

**Issue by NihadBadalov** [go-telegram/bot#81]
I tried following the [inline keyboard example here](https://github.com/go-telegram/bot/blob/main/examples/inline_keyboard/main.go). Use [this gist](https://gist.github.com/NihadBadalov/5eb3d5f776f37d2aa3b49133b11da06a) for reference.

After writing "yep" in the chat to the bot, the buttons do get printed:
<img width="188" alt="image" src="https://github.com/go-telegram/bot/assets/32594553/0460d91d-c9f4-4c68-960a-e0a344da3981">

However, when I click the buttons, the `fmt.Println(...)` on line 116 doesn't get printed - the function doesn't get executed at all. What is wrong?

Help will be appreciated! Thanks in advance.

**Comment by negasus** [comment]
Your example (with some fixes for omit `oris/commands`) correctly works for me
[gist](https://gist.github.com/negasus/010aa334d857201a1fbea7e2f83e87b7)

**Comment by NihadBadalov** [comment]
Still doesn't work for me. Even tried the code in the gist you sent
![image](https://github.com/go-telegram/bot/assets/32594553/1174cd48-22d2-45da-8ee6-79687c8d1368)

**Comment by NihadBadalov** [comment]
Resetting the bot's token helped
