### ISSUE TITLE
Able to connect bot to the test network

### ISSUE THREAD

**Issue by saneqq** [go-telegram/bot#89]
The test environment is completely separate from the main environment, so you will need to create a new user account and a new bot with @BotFather. This is very convenient when connecting a web app with a bot
https://docs.ton.org/develop/dapps/telegram-apps/testing-apps
examples https://docs.pyrogram.org/topics/test-servers

**Comment by negasus** [comment]
What actions are required for this support?

**Comment by fvbock** [comment]
Hi @negasus 

ran into the same question as @saneqq 

Bot API 6.0 introduced [the test environment](https://core.telegram.org/bots/webapps#using-bots-in-the-test-environment)

```
After receiving your bot token, you can send requests to the Bot API in this format:

https://api.telegram.org/bot<token>/test/METHOD_NAME
```

so i guess to support that it would need a flag - eg `UseTestEnvironment` - to pass to `bot.New` - using bot tokens created with an account in the test env get rejected by as `Unauthorized` when initializing the bot.

**Comment by fvbock** [comment]
thanks @negasus !

works well.
